import 'custom_entity.dart';

final List<CustomEntity> publishIndust = [
  CustomEntity(value: 0, label: "未设置", selected: true),
  CustomEntity(value: 1, label: "保密", selected: false),
  CustomEntity(value: 2, label: "IT|通信|互联网", selected: false),
  CustomEntity(value: 3, label: "机械机电|自动化", selected: false),
  CustomEntity(value: 4, label: "专业服务", selected: false),
  CustomEntity(value: 5, label: "冶金冶炼|五金|采掘", selected: false),
  CustomEntity(value: 6, label: "化工行业", selected: false),
  CustomEntity(value: 7, label: "纺织服装|皮革鞋帽", selected: false),
  CustomEntity(value: 8, label: "电子电器|仪器仪表", selected: false),
  CustomEntity(value: 9, label: "快消品|办公用品", selected: false),
  CustomEntity(value: 10, label: "房产|建筑|城建|环保", selected: false),
  CustomEntity(value: 11, label: "金融行业", selected: false),
  CustomEntity(value: 12, label: "制药|医疗", selected: false),
  CustomEntity(value: 13, label: "生活服务|娱乐休闲", selected: false),
  CustomEntity(value: 14, label: "交通工具|运输物流", selected: false),
  CustomEntity(value: 15, label: "批发|零售|贸易", selected: false),
  CustomEntity(value: 16, label: "广告|媒体", selected: false),
  CustomEntity(value: 17, label: "教育|科研|培训", selected: false),
  CustomEntity(value: 18, label: "造纸|印刷", selected: false),
  CustomEntity(value: 19, label: "包装|工艺礼品|奢侈品", selected: false),
  CustomEntity(value: 20, label: "营销|销售人员", selected: false),
  CustomEntity(value: 21, label: "能源|资源", selected: false),
  CustomEntity(value: 22, label: "农|林|牧|渔", selected: false),
  CustomEntity(value: 23, label: "政府|非赢利机构|其他", selected: false),
  CustomEntity(value: 24, label: "其他", selected: false)
];

final List<CustomEntity> industryList = [
  CustomEntity(value: 0, label: "全部行业", selected: true),
  CustomEntity(value: 1, label: "保密", selected: false),
  CustomEntity(value: 2, label: "IT|通信|互联网", selected: false),
  CustomEntity(value: 3, label: "机械机电|自动化", selected: false),
  CustomEntity(value: 4, label: "专业服务", selected: false),
  CustomEntity(value: 5, label: "冶金冶炼|五金|采掘", selected: false),
  CustomEntity(value: 6, label: "化工行业", selected: false),
  CustomEntity(value: 7, label: "纺织服装|皮革鞋帽", selected: false),
  CustomEntity(value: 8, label: "电子电器|仪器仪表", selected: false),
  CustomEntity(value: 9, label: "快消品|办公用品", selected: false),
  CustomEntity(value: 10, label: "房产|建筑|城建|环保", selected: false),
  CustomEntity(value: 11, label: "金融行业", selected: false),
  CustomEntity(value: 12, label: "制药|医疗", selected: false),
  CustomEntity(value: 13, label: "生活服务|娱乐休闲", selected: false),
  CustomEntity(value: 14, label: "交通工具|运输物流", selected: false),
  CustomEntity(value: 15, label: "批发|零售|贸易", selected: false),
  CustomEntity(value: 16, label: "广告|媒体", selected: false),
  CustomEntity(value: 17, label: "教育|科研|培训", selected: false),
  CustomEntity(value: 18, label: "造纸|印刷", selected: false),
  CustomEntity(value: 19, label: "包装|工艺礼品|奢侈品", selected: false),
  CustomEntity(value: 20, label: "营销|销售人员", selected: false),
  CustomEntity(value: 21, label: "能源|资源", selected: false),
  CustomEntity(value: 22, label: "农|林|牧|渔", selected: false),
  CustomEntity(value: 23, label: "政府|非赢利机构|其他", selected: false),
  CustomEntity(value: 24, label: "其他", selected: false)
];

final List<CustomEntity> missionTagsList = [
  CustomEntity(value: 0, label: "全部类型"),
  CustomEntity(value: 1, label: "家教"),
  CustomEntity(value: 2, label: "跑腿"),
  CustomEntity(value: 3, label: "代购"),
  CustomEntity(value: 4, label: "维修"),
  CustomEntity(value: 5, label: "设计"),
  CustomEntity(value: 6, label: "制造"),
  CustomEntity(value: 7, label: "收购"),
  CustomEntity(value: 8, label: "翻译"),
  CustomEntity(value: 9, label: "程序"),
  CustomEntity(value: 10, label: "APP"),
  CustomEntity(value: 11, label: "建筑设计"),
  CustomEntity(value: 12, label: "景观设计"),
  CustomEntity(value: 13, label: "小程序"),
  CustomEntity(value: 14, label: "编程"),
  CustomEntity(value: 15, label: "开发"),
  CustomEntity(value: 16, label: "搬家"),
  CustomEntity(value: 17, label: "货运"),
  CustomEntity(value: 18, label: "JAVA"),
  CustomEntity(value: 19, label: "PYTHON"),
  CustomEntity(value: 20, label: "C++"),
  CustomEntity(value: 21, label: "装修设计"),
  CustomEntity(value: 22, label: "造价"),
  CustomEntity(value: 23, label: "财务"),
  CustomEntity(value: 24, label: "游戏"),
  CustomEntity(value: 25, label: "其他")
];
